version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: bitiron-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitiron_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: bitiron-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=bitiron_db
      - DB_PORT=3306
      - PORT=3000
    depends_on:
      - db

volumes:
  mariadb_data:
